// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddkfnwadwjqeltstkqnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRka2Zud2Fkd2pxZWx0c3RrcW51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTc3ODMsImV4cCI6MjA2NjY3Mzc4M30.V5BWkGlAoDgGzQmDTOkPzyjy2BWNMCFtIlLQGbcOsYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);